package at.orchaldir.gm.core.model.item.equipment

import at.orchaldir.gm.core.model.util.part.CLOTHING_MATERIALS
import at.orchaldir.gm.core.model.util.part.FRAGILE_MATERIALS
import at.orchaldir.gm.core.model.util.part.MADE_FROM_METALS
import at.orchaldir.gm.core.model.util.part.SOLID_MATERIALS

// clothing

val BELT_STRAP_MATERIALS = CLOTHING_MATERIALS
val DRESS_MATERIALS = CLOTHING_MATERIALS
val EYE_PATCH_MATERIALS = CLOTHING_MATERIALS
val FOOTWEAR_MATERIALS = CLOTHING_MATERIALS
val GLOVES_MATERIALS = CLOTHING_MATERIALS
val HAT_MATERIALS = CLOTHING_MATERIALS
val LAMELLAR_STRIPE_MATERIALS = CLOTHING_MATERIALS
val PANTS_MATERIALS = CLOTHING_MATERIALS
val SHIRT_MATERIALS = CLOTHING_MATERIALS
val SKIRT_MATERIALS = CLOTHING_MATERIALS
val SLING_MATERIALS = CLOTHING_MATERIALS
val TIE_MATERIALS = CLOTHING_MATERIALS

// fragile

val IOUN_STONE_MATERIALS = FRAGILE_MATERIALS
val ORNAMENT_MATERIALS = FRAGILE_MATERIALS

// metal

val ARMOR_PLATE_MATERIALS = MADE_FROM_METALS
val BLADE_MATERIALS = MADE_FROM_METALS
val BOOK_PROTECTION_MATERIALS = MADE_FROM_METALS
val CHAIN_MAIL_MATERIALS = MADE_FROM_METALS
val HEAD_FIXATION_MATERIALS = MADE_FROM_METALS
val HELMET_MATERIALS = MADE_FROM_METALS
val SPIKE_MATERIALS = MADE_FROM_METALS
val ZIPPER_MATERIALS = MADE_FROM_METALS

// solid

val ARMOR_SCALE_MATERIALS = SOLID_MATERIALS
val CLUB_HEAD_MATERIALS = SOLID_MATERIALS
val BOW_MATERIALS = SOLID_MATERIALS
val BUCKLE_MATERIALS = SOLID_MATERIALS
val BUTTON_MATERIALS = SOLID_MATERIALS
val GLASSES_FRAME_MATERIALS = SOLID_MATERIALS
val GRIP_MATERIALS = SOLID_MATERIALS
val GUARD_MATERIALS = SOLID_MATERIALS
val SEGMENT_MATERIALS = SOLID_MATERIALS
val SHAFT_MATERIALS = SOLID_MATERIALS
val SHIELD_MATERIALS = SOLID_MATERIALS
val SPEAR_MATERIALS = SOLID_MATERIALS
