package at.orchaldir.gm.app.parse

const val FAMILY_NAMES = "family_names"
const val HAIR_STYLE = "hair_style"
const val BEARD_STYLE = "beard_style"
const val GENONYMIC_STYLE = "genonymic_style"
const val GOATEE_STYLE = "goatee_style"
const val LIP_COLORS = "lip_colors"
const val LOOKUP_DISTANCE = "lookup_distance"
const val MIDDLE_NAME = "middle_name"
const val MOUSTACHE_STYLE = "moustache_style"
const val NAME_ORDER = "name_order"
const val NAME = "name"
const val NAMES = "names"
const val NAMING_CONVENTION = "naming_convention"
const val WORD = "word"
