package at.orchaldir.gm.app.parse

const val BEARD_STYLE = "beard_style"
const val CULTURE = "culture"
const val FAMILY_NAME = "family_name"
const val FAMILY_NAMES = "family_names"
const val FATHER = "father"
const val GENONYMIC_STYLE = "genonymic_style"
const val GENDER = "gender"
const val GIVEN_NAME = "given_name"
const val GOATEE_STYLE = "goatee_style"
const val GROUP_PREFIX = "group_"
const val HAIR_STYLE = "hair_style"
const val LIP_COLORS = "lip_colors"
const val LOOKUP_DISTANCE = "lookup_distance"
const val MIDDLE_NAME = "middle_name"
const val NONE = "None"
const val MOTHER = "mother"
const val MOUSTACHE_STYLE = "moustache_style"
const val NAME_ORDER = "name_order"
const val NAME_TYPE = "name_type"
const val NAME = "name"
const val NAMES = "names"
const val NAMING_CONVENTION = "naming_convention"
const val ORIGIN = "origin"
const val RACE = "race"
const val WORD = "word"
